version: "3"
services: 
  node_app:
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/app/
      - /home/app/node_modules/
    build:
      context: .
      args: 
        - NODE_ENV=development
      dockerfile: Dockerfile
    command: npm run dev2  # this will override the CMD in Dockerfile