version: "3"
services: 
  node_app:
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/home/app/src
      - /home/app/node_modules/
    build:
      context: .
      args: 
        - NODE_ENV=production
      dockerfile: Dockerfile
    command: npm start